### ISSUE TITLE
bound svg2png errored when running npm run dev (node 7 & npm v3.10.8 & win 10)

### ISSUE THREAD

**Issue by rmaroun** [localnerve/react-pwa-reference#282] opened 2016-11-05 11:31 UTC
'bound svg2png' errored after 1.19 s
[12:28:40] Error in plugin 'gulp-svg2png'
Message:
    Error while converting image.Error: TypeError: 'undefined' is not a function (evaluating 'el.getBBox()')

  phantomjs://webpage.evaluate():5
  phantomjs://webpage.evaluate():35
  phantomjs://webpage.evaluate():35
Unable to calculate dimensions.
TypeError: 'null' is not an object (evaluating 'dimensions.width')
Details:
    domain: [object Object]
    domainThrown: true
[12:28:40] 'ccss' errored after 1.28 s
[12:28:40] 'dev' errored after 2.82 s
[12:28:40] The following tasks did not complete: mainBundles
[12:28:40] Did you forget to signal async completion?

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-pwa-reference@0.1.0 dev: `npm run lint && gulp dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-pwa-reference@0.1.0 dev script 'npm run lint && gulp dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-pwa-reference package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && gulp dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-pwa-reference
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-pwa-reference
npm ERR! There is likely additional logging output above.

**Comment by localnerve** [comment] 2016-11-05 11:51
Interesting. Can you verify what version of svg2png and gulp-svg2png is actually running on your installation?
I looked at the svg2png code, and [this](https://github.com/domenic/svg2png/blob/50ce06bba27c2408b22d620371ecbf28e4e50cb6/lib/converter.js#L119) is the closest thing to getBBox I found. It doesn't seem to match up.

**Comment by rmaroun** [comment] 2016-11-05 12:13
Thanks a lot @localnerve for your prompt reply. I will then work with node 6 for now which is also the version supported by AWS elactic beanstalk.

**Comment by localnerve** [comment] 2016-11-05 12:16
Ok, please let me know if this is still flaky. If it is for you, I'm going
to run into this too pretty soon, so this will require attention.

**Comment by localnerve** [comment] 2016-11-05 12:26
@rmaroun It is also possible that supporting a svg fallback doesn't make sense anymore at all: http://caniuse.com/#search=svg
The reference is React 15 after all.
Interested to hear your thoughts on this idea?

**Comment by rmaroun** [comment] 2016-11-05 12:39
@localnerve indeed all browsers seem to support svg out of the box so maintaining and supporting and svg fallback is not needed. Btw, I sill have the same issue with gulp-svg2png plugin using node 6.9.1 and npm 3.10.8. Do I need to use any specific version of node and npm to make it work? Thanks.

**Comment by localnerve** [comment] 2016-11-05 12:45
Can you please do a quick experiment?
In pkg.json, update gulp-svg2png to 2.0.2, run `npm install` to update it. 
Run `npm run build:server` to run the code
Regardless of the ultimate direction, I'd like to know the result of that.

**Comment by rmaroun** [comment] 2016-11-05 12:51
It seems to work better! It did run the full script 'build:server' till the end but with the following message:

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error in plugin 'gulp-svg2png'
Message:
    Error while converting the image: Width or height could not be determined from either the source file or the supplied dimensions

  phantomjs://code/converter.js:46 in onLoadFinished
[13:48:49] Finished 'mainBundles' after 17 s
[13:48:49] The following tasks did not complete: build, <parallel>, ccss, <parallel>, bound svg2png
[13:48:49] Did you forget to signal async completion?
```

**Comment by rmaroun** [comment] 2016-11-05 12:55
When running `npm run dev` I have the following issue:
```
[13:52:07] Requiring external module babel-register
[13:52:09] Using gulpfile c:\xx\webapp1\gulpfile.babel.js
[13:52:09] Starting 'dev'...
[13:52:09] Starting 'setup'...
[13:52:09] Finished 'setup' after 32 ms
[13:52:09] Starting 'clean'...
[13:52:09] Finished 'clean' after 24 ms
[13:52:09] Starting 'copy'...
[13:52:09] Finished 'copy' after 146 ms
[13:52:09] Starting 'imagemin'...
(node:25380) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
[13:52:10] gulp-imagemin: Minified 31 images (saved 23.5 kB - 1.8%)
[13:52:10] Finished 'imagemin' after 1.32 s
[13:52:10] Starting 'ccss'...
[13:52:10] Starting 'mainBundles'...
[13:52:10] Starting 'bound svg2png'...
[13:52:10] Starting 'bound svgmin'...
[13:52:11] Finished 'bound svgmin' after 650 ms
(node:25380) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error in plugin 'gulp-svg2png'
Message:
    Error while converting the image: Width or height could not be determined from either the source file or the supplied dimensions

  phantomjs://code/converter.js:46 in onLoadFinished
[13:52:23] Finished 'mainBundles' after 13 s
[13:52:24] The following tasks did not complete: dev, <parallel>, ccss, <parallel>, bound svg2png
[13:52:24] Did you forget to signal async completion?
```

**Comment by rmaroun** [comment] 2016-11-05 13:12
Error when running npm start:

```
> react-pwa-reference@0.1.0 start c:\xx\webapp1
> node -e 'process.env.NODE_ENV=process.env.NODE_ENV || "production"; require("./output/application/server");'

[eval]:1
'process.env.NODE_ENV=process.env.NODE_ENV
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at bootstrap_node.js:357:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
'"production"' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-pwa-reference@0.1.0 start: `node -e 'process.env.NODE_ENV=process.env.NODE_ENV || "production"; require("./output/application/server");'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-pwa-reference@0.1.0 start script 'node -e 'process.env.NODE_ENV=process.env.NODE_ENV || "production"; require("./output/application/server");''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-pwa-reference package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e 'process.env.NODE_ENV=process.env.NODE_ENV || "production"; require("./output/application/server");'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-pwa-reference
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-pwa-reference
npm ERR! There is likely additional logging output above.
```

**Comment by localnerve** [comment] 2016-11-05 13:18
Yea, that was my result too. 
OK, a change is required here. Give me a bit to decide on direction(s).

In the interim, to run this immediately, you can replace the src/build/ccss.js file with [this](https://gist.github.com/localnerve/2491bec305581e84ab62fa2ee927fc01) version that omits the svg2png fallback creation step.

**Comment by localnerve** [comment] 2016-11-05 13:26
In regard to the `npm start` issue, does it make a difference for you if the RHS of the node env assignment is an expression?

Please try replacing the `npm start` (package.json line 46) script with this:
```
"start": "node -e 'process.env.NODE_ENV=(process.env.NODE_ENV || \"production\"); require(\"./output/application/server\");'",
```

**Comment by rmaroun** [comment] 2016-11-05 13:31
Replaced it but still same issue:
```
> react-pwa-reference@0.1.0 start c:\xx\webapp1
> node -e 'process.env.NODE_ENV=(process.env.NODE_ENV || "production"); require("./output/application/server");'

[eval]:1
'process.env.NODE_ENV=(process.env.NODE_ENV
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at bootstrap_node.js:357:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
'"production")' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by localnerve** [comment] 2016-11-05 14:17
The purpose of that bit is to allow you to set node_env elsewhere, but if you didn't, to default to "production".

Sourced from an [old Angular technique](https://github.com/angular-fullstack/generator-angular-fullstack/issues/607#issuecomment-57426614).

Looking at the error more closely, it seems like the script is getting truncated unexpectedly at the `||`, dividing `process.env.NODE_ENV=(process.env.NODE_ENV` into an incomplete statement and `"production"` into a separate command, given to the windows cmd interpreter.

So in Windows, it would appear the eval script `-e` is getting interpreted by the shell prior to being given to Node, so some additional escape required beyond `'` (single quote) to prevent unwanted shell interpretation will be required. 

If memory serves, for Windows, this is a[ `^`](http://ss64.com/nt/syntax-esc.html), but putting that (`^||`) into the JS will be a problem for everyone else, because it won't be removed prior to JS eval like it will in Windows.

My recommendation (for now) is to use this replacement for package.json line 46:
```
    "start": "cross-env NODE_ENV=production && node -e 'require(\"./output/application/server\");'",
```
I'll need to figure out a different way of allowing node_env to be overridden for `npm start`.

**Comment by rmaroun** [comment] 2016-11-05 16:23
Thanks @localnerve! Now the script is running properly but at the end no node server started on any port, it just end the command like nothing happened when running the following command:

`node -e 'require("./output/application/server");'`

**Comment by localnerve** [comment] 2016-11-05 16:32
Yuck, no output for `npm start` AND no server started?

Maybe cross-env was a bad idea. 👎

**Comment by rmaroun** [comment] 2016-11-05 16:46
nothing at all :(

**Comment by localnerve** [comment] 2016-11-05 17:01
I'm setting up a windows VM right now.

**Comment by rmaroun** [comment] 2016-11-05 17:25
Super! thanks @localnerve

**Comment by localnerve** [comment] 2016-11-05 17:51
OK, I'm running into all kinds of git environment problems on the VM. I'm going to have to pick this up again later.

A couple of lingering questions:

* Do you have access to git-for-windows git bash? Is that in-appropriate in this situation?
* Can you replicate this problem in your normal Windows environment by manually setting NODE_ENV and PORT and then running the `node -e 'require(\"./output/application/server\");'`
* Can you isolate the issue in your environment by inserting console commands into `output/application/server/index.js`?

**Comment by rmaroun** [comment] 2016-11-05 21:20
it is working with the following manual steps that set NODE_ENV and PORT variables:
`set NODE_ENV=production`
you can check if the value is set using the following command:
`echo %NODE_ENV% // should prompt production`
same for PORT
`set PORT=3000`
you can check if the value is set using the following command:
`echo %PORT% // should prompt 3000`
then I had to run the following command to start the server:
`node ./output/application/server/index.js`

**The server is now starting and I can load the application.**

Do you have any tutorial on how to start from scratch with a new app?
Thank you @localnerve

**Comment by localnerve** [comment] 2016-11-05 21:58
This is useful info, thank you. I think this should be more accessible, however. 

I do not have a tutorial on this, as I've been just using it as a reference application.
Maybe you can email me some things you would like to see covered?
Where to start is subjective (depends on what you want to see), so more info on that would be helpful. Some people want to see isomorphic flux, some want service worker, etc.
Maybe a tutorial starts with a menu on the ideas and functional things this covers in reference...

As for your experience here, I would still like to reproduce it for myself.
Can you please include the following so I can reproduce?
* What Git app did you use
* What command line interpreter

Thanks again for your info.

**Comment by rmaroun** [comment] 2016-11-05 22:08
@localnerve just updated my last comment with the requested information about git and command line interpreter. For the rest I will get back to you.

**Comment by localnerve** [comment] 2016-12-19 19:05
@rmaroun I finally got around to making a reasonable Windows platform to cross check things with. The following commits allowed running/usage/dev, and I *think* addresses everything - At least what we discussed:
884c22c247fbf28a4f82a43e044b1f3a74c68cbf
a4fda1a80ca2bb19cc7e4e79d4d6d8c20a0ec6f0
1b86598cd9120523f9e0411f65619969b1ff1285
 
A clean clone/install of the repo works for fresh Windows VMs, Node 6, so I'm closing this issue. Please reopen or create a new one if you discover something was missed.

Thanks for your attention on this.
Alex

**Closed by localnerve** 2016-12-19 19:05 UTC
